//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.34014
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using rayav_csharp;
using UnityEditor;

namespace RayaUtility
{
	public class RayaUtility
	{
		public static rayav_csharp.Vector3 fromUnityVector3(UnityEngine.Vector3 unityVector)
		{
			return new rayav_csharp.Vector3(unityVector.x, unityVector.y, unityVector.z);
		}
	}
}

